algoritmo "areaquadrada"
// Função : Este programa solicita um valore calcula a area do quadrado
// Autor :  Leonardo Zaia Silva
// Data : 01/03/2024
// Seção de Declarações 
var

areaQ:real
lado:real


inicio
//entrada

escreva ("Qual o lado do Quadrado?")
leia (lado)



//processamento
areaQ <- lado * lado

//saida

escreva ("A area do quadrado é: ",areaQ)


fimalgoritmo
